### ISSUE TITLE
Cannot Compile in Xcode 6.1.1

### ISSUE THREAD

**Issue by philipamour** [joeblau/Dust#2]
![screen shot 2015-02-04 at 11 17 41 am](https://cloud.githubusercontent.com/assets/4676105/6039490/76246586-ac5f-11e4-8199-ad1b4976f5b0.png)

**Comment by joeblau** [comment]
Sorry about that, it should be fixed now.  The PKHUD project has some crazy installation instructions that don't actually work concurrently for Simulator, Device, and Archiving *unless* you add the framework's source code as a target.

**Comment by philipamour** [comment]
Thanks, seems to be fixed now. :+1:
